### ISSUE TITLE
dataset is missing

### ISSUE THREAD

**Issue by pjpjq** [tgbnhy/torch-trajectory#2]
The google drive link shows access denied. Could you please share it again?

**Comment by tgbnhy** [comment]
https://drive.google.com/open?id=11sA9AYLKrD5T34gL3_hFb_HtIDHb7oZ5

Please try this one and let me know whether it works.

**Comment by pjpjq** [comment]
Thanks, I requested and got access later yesterday. BTW, is the Beijing data also available?

**Comment by tgbnhy** [comment]
https://drive.google.com/open?id=1nmQmawGxXgdx8dH_0qqVXiGycTcjRV6Y

**Comment by tgbnhy** [comment]
Hi, may I know what research problem you want to solve? Maybe we can discuss it and cooperate.

**Comment by wendingp** [comment]
> Hi, may I know what research problem you want to solve? Maybe we can discuss it and cooperate.

That'd be great! Actually I'm doing my final year project based on this repo, if you are interested, you can add my wechat: 815689327
